version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306  
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: BankDB
    networks:
      - bankapp
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  bankapp:
    container_name: BankApp
    image: amankumar19/springboot-bankapp:latest
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/BankDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      SPRING_DATASOURCE_PASSWORD: Test@123
    networks:
      - bankapp
    depends_on:
      - mysql 
    restart: always

volumes:
  mysql-data:

networks:
  bankapp: 
